UNLOCKAURORA()

AU:NewDefaults('interface', {
    version = {value = '1.0'},
    enabled = {value = true},
    gui = {
        {indexRange = {1, 1}, tab = 'interface', subtab = 1},
    },
})

AU:NewModule('interface', 1, function()
    local interfaceFrame = AU.ui.CreatePaperDollFrame('AU_InterfaceFrame', UIParent, 850, 600, 2)
    interfaceFrame:SetPoint('CENTER', UIParent, 'CENTER', 0, 50)
    interfaceFrame:EnableMouse(true)
    interfaceFrame:Hide()

    local closeButton = AU.ui.CreateRedButton(interfaceFrame, 'close', function() interfaceFrame:Hide() end)
    closeButton:SetPoint('TOPRIGHT', interfaceFrame, 'TOPRIGHT', 0, -1)

    local header = AU.ui.Font(interfaceFrame, 12, 'Interface', {1, 1, 1}, 'CENTER')
    header:SetPoint('TOP', interfaceFrame, 'TOP', 0, -6)

    table.insert(UISpecialFrames, interfaceFrame:GetName())

    local basicPanel = CreateFrame('Frame', nil, interfaceFrame)
    basicPanel:SetAllPoints(interfaceFrame)

    local advancedPanel = CreateFrame('Frame', nil, interfaceFrame)
    advancedPanel:SetAllPoints(interfaceFrame)
    advancedPanel:Hide()

    local controlsFrame = CreateFrame('Frame', nil, basicPanel)
    controlsFrame:SetWidth(10)
    controlsFrame:SetHeight(150)
    controlsFrame:SetPoint('TOPLEFT', interfaceFrame, 'TOPLEFT', 32, -40)
    controlsFrame:SetPoint('TOPRIGHT', interfaceFrame, 'TOPRIGHT', -32, -0)
    local controlsTitle = AU.ui.Font(controlsFrame, 10, 'Controls', {1, 0.82, 0}, 'LEFT')
    controlsTitle:SetPoint('TOPLEFT', controlsFrame, 'TOPLEFT', 5, -5)

    local mouseSlider = AU.ui.Slider(controlsFrame, 'mouse', 'Mouse Speed', 1, 10, 1, '%.0f', 90, 16)
    mouseSlider:SetPoint('TOPLEFT', controlsTitle, 'BOTTOMLEFT', 15, -10)
    local autoLootCheck = AU.ui.Checkbox(controlsFrame, 'Auto Loot', 16, 16, 'RIGHT')
    autoLootCheck:SetPoint('TOPLEFT', mouseSlider, 'BOTTOMLEFT', 2, -18)

    local clickMoveCheck = AU.ui.Checkbox(controlsFrame, 'Click to Move', 16, 16, 'RIGHT')
    clickMoveCheck:SetPoint('TOPLEFT', controlsFrame, 'TOP', -80, -25)
    local autoSelfCheck = AU.ui.Checkbox(controlsFrame, 'Auto Self Cast', 16, 16, 'RIGHT')
    autoSelfCheck:SetPoint('TOP', clickMoveCheck, 'BOTTOM', 0, 0)
    local dismountCheck = AU.ui.Checkbox(controlsFrame, 'Auto Dismount', 16, 16, 'RIGHT')
    dismountCheck:SetPoint('TOP', autoSelfCheck, 'BOTTOM', 0, 0)

    local attackCheck = AU.ui.Checkbox(controlsFrame, 'Sticky Targeting', 16, 16, 'RIGHT')
    attackCheck:SetPoint('TOPLEFT', controlsFrame, 'TOPRIGHT', -220, -25)
    local assistCheck = AU.ui.Checkbox(controlsFrame, 'Auto Assist', 16, 16, 'RIGHT')
    assistCheck:SetPoint('TOP', attackCheck, 'BOTTOM', 0, 0)

    local cameraCheck = AU.ui.Checkbox(controlsFrame, 'Camera Following', 16, 16, 'RIGHT')
    cameraCheck:SetPoint('TOPLEFT', autoLootCheck, 'TOPLEFT', 2, 0)

    local cameraDropdown = AU.ui.Dropdown(controlsFrame, 'Camera Style', 90, 20)
    cameraDropdown:SetPoint('TOPLEFT', cameraCheck, 'TOPLEFT', 153, 0)

    local displayFrame = CreateFrame('Frame', nil, basicPanel)
    displayFrame:SetWidth(10)
    displayFrame:SetHeight(155)
    displayFrame:SetPoint('TOPLEFT', controlsFrame, 'BOTTOMLEFT', 0, 20)
    displayFrame:SetPoint('TOPRIGHT', controlsFrame, 'BOTTOMRIGHT', 0, 20)
    local displayTitle = AU.ui.Font(displayFrame, 10, 'Display', {1, 0.82, 0}, 'LEFT')
    displayTitle:SetPoint('TOPLEFT', displayFrame, 'TOPLEFT', 5, -5)

    local tooltipCheck = AU.ui.Checkbox(displayFrame, 'Show Tooltips', 16, 16, 'RIGHT')
    tooltipCheck:SetPoint('TOPLEFT', displayTitle, 'BOTTOMLEFT', 5, -5)
    local healthCheck = AU.ui.Checkbox(displayFrame, 'Show Health', 16, 16, 'RIGHT')
    healthCheck:SetPoint('TOP', tooltipCheck, 'BOTTOM', 0, 0)
    local manaCheck = AU.ui.Checkbox(displayFrame, 'Show Mana', 16, 16, 'RIGHT')
    manaCheck:SetPoint('TOP', healthCheck, 'BOTTOM', 0, 0)
    local targetCheck = AU.ui.Checkbox(displayFrame, 'Target of Target', 16, 16, 'RIGHT')
    targetCheck:SetPoint('TOP', manaCheck, 'BOTTOM', 0, 0)
    local petCheck = AU.ui.Checkbox(displayFrame, 'Pet Frame', 16, 16, 'RIGHT')
    petCheck:SetPoint('TOP', targetCheck, 'BOTTOM', 0, 0)

    local namesCheck = AU.ui.Checkbox(displayFrame, 'Unit Names', 16, 16, 'RIGHT')
    namesCheck:SetPoint('TOPLEFT', displayFrame, 'TOP', -80, -25)
    local guildsCheck = AU.ui.Checkbox(displayFrame, 'Guild Names', 16, 16, 'RIGHT')
    guildsCheck:SetPoint('TOP', namesCheck, 'BOTTOM', 0, 0)
    local titlesCheck = AU.ui.Checkbox(displayFrame, 'Player Titles', 16, 16, 'RIGHT')
    titlesCheck:SetPoint('TOP', guildsCheck, 'BOTTOM', 0, 0)
    local levelCheck = AU.ui.Checkbox(displayFrame, 'Show Levels', 16, 16, 'RIGHT')
    levelCheck:SetPoint('TOP', titlesCheck, 'BOTTOM', 0, 0)
    local npcCheck = AU.ui.Checkbox(displayFrame, 'NPC Names', 16, 16, 'RIGHT')
    npcCheck:SetPoint('TOP', levelCheck, 'BOTTOM', 0, 0)

    local buffCheck = AU.ui.Checkbox(displayFrame, 'Buff Durations', 16, 16, 'RIGHT')
    buffCheck:SetPoint('TOPLEFT', displayFrame, 'TOPRIGHT', -220, -25)
    local debuffCheck = AU.ui.Checkbox(displayFrame, 'Debuff Durations', 16, 16, 'RIGHT')
    debuffCheck:SetPoint('TOP', buffCheck, 'BOTTOM', 0, 0)
    local castbarCheck = AU.ui.Checkbox(displayFrame, 'Show Castbar', 16, 16, 'RIGHT')
    castbarCheck:SetPoint('TOP', debuffCheck, 'BOTTOM', 0, 0)
    local partyCheck = AU.ui.Checkbox(displayFrame, 'Party Background', 16, 16, 'RIGHT')
    partyCheck:SetPoint('TOP', castbarCheck, 'BOTTOM', 0, 0)
    local raidCheck = AU.ui.Checkbox(displayFrame, 'Raid Frames', 16, 16, 'RIGHT')
    raidCheck:SetPoint('TOP', partyCheck, 'BOTTOM', 0, 0)

    local cameraFrame = CreateFrame('Frame', nil, basicPanel)
    cameraFrame:SetWidth(10)
    cameraFrame:SetHeight(115)
    cameraFrame:SetPoint('TOPLEFT', displayFrame, 'BOTTOMLEFT', 0, 20)
    cameraFrame:SetPoint('TOPRIGHT', displayFrame, 'BOTTOMRIGHT', 0, 20)
    local cameraTitle = AU.ui.Font(cameraFrame, 10, 'Camera', {1, 0.82, 0}, 'LEFT')
    cameraTitle:SetPoint('TOPLEFT', cameraFrame, 'TOPLEFT', 5, -5)

    local followDropdown = AU.ui.Dropdown(cameraFrame, 'Follow Style', 90, 20)
    followDropdown:SetPoint('TOPLEFT', cameraTitle, 'BOTTOMLEFT', 0, -19)
    local waterCheck = AU.ui.Checkbox(cameraFrame, 'Water Collision', 16, 16, 'RIGHT')
    waterCheck:SetPoint('TOPLEFT', followDropdown, 'BOTTOMLEFT', 20, 0)
    local smartCheck = AU.ui.Checkbox(cameraFrame, 'Smart Pivot', 16, 16, 'RIGHT')
    smartCheck:SetPoint('TOP', waterCheck, 'BOTTOM', 0, 0)

    local distSlider = AU.ui.Slider(cameraFrame, 'dist', 'Max Distance', 1, 50, 1, '%.0f', 90, 16)
    distSlider:SetPoint('TOPLEFT', cameraFrame, 'TOP', -20, -14)
    local bobCheck = AU.ui.Checkbox(cameraFrame, 'Head Bob', 16, 16, 'RIGHT')
    bobCheck:SetPoint('TOPLEFT', distSlider, 'BOTTOMLEFT', 0, -15)
    local shakeCheck = AU.ui.Checkbox(cameraFrame, 'Camera Shake', 16, 16, 'RIGHT')
    shakeCheck:SetPoint('TOP', bobCheck, 'BOTTOM', 0, 0)

    local fovSlider = AU.ui.Slider(cameraFrame, 'fov', 'Field of View', 1, 10, 1, '%.0f', 90, 16)
    fovSlider:SetPoint('TOPLEFT', cameraFrame, 'TOPRIGHT', -215, -14)
    local terrainSlider = AU.ui.Slider(cameraFrame, 'terrain', 'Terrain Tilt', 1, 10, 1, '%.0f', 90, 16)
    terrainSlider:SetPoint('TOP', fovSlider, 'BOTTOM', 0, -27)

    local helpFrame = CreateFrame('Frame', nil, basicPanel)
    helpFrame:SetWidth(10)
    helpFrame:SetHeight(70)
    helpFrame:SetPoint('TOPLEFT', cameraFrame, 'BOTTOMLEFT', 0, -20)
    helpFrame:SetPoint('TOPRIGHT', cameraFrame, 'BOTTOMRIGHT', 0, -20)
    local helpTitle = AU.ui.Font(helpFrame, 10, 'Help', {1, 0.82, 0}, 'LEFT')
    helpTitle:SetPoint('TOPLEFT', helpFrame, 'TOPLEFT', 5, -5)

    local tutorialCheck = AU.ui.Checkbox(helpFrame, 'Show Tutorials', 16, 16, 'RIGHT')
    tutorialCheck:SetPoint('TOPLEFT', helpTitle, 'BOTTOMLEFT', 5, -5)
    local beginnerCheck = AU.ui.Checkbox(helpFrame, 'Beginner Tooltips', 16, 16, 'RIGHT')
    beginnerCheck:SetPoint('TOPLEFT', tutorialCheck, 'BOTTOMLEFT', 0, 0)

    local resetButton = AU.ui.Button(helpFrame, 'Reset Tutorials', 120, 25)
    resetButton:SetPoint('TOPLEFT', helpFrame, 'TOP', -60, -17)
    resetButton:SetScript('OnClick', function() end)

    local errorCheck = AU.ui.Checkbox(helpFrame, 'Show Errors', 16, 16, 'RIGHT')
    errorCheck:SetPoint('LEFT', resetButton, 'RIGHT', 50, 0)

    local okButton = AU.ui.Button(interfaceFrame, 'Okay', 100, 30)
    okButton:SetPoint('BOTTOMRIGHT', interfaceFrame, 'BOTTOMRIGHT', -10, 10)
    okButton:SetScript('OnClick', function() interfaceFrame:Hide() end)

    local defaultsButton = AU.ui.Button(interfaceFrame, 'Defaults', 100, 30)
    defaultsButton:SetPoint('RIGHT', okButton, 'LEFT', -5, 0)
    defaultsButton:SetScript('OnClick', function() end)

    local chatCol = CreateFrame('Frame', nil, advancedPanel)
    chatCol:SetWidth(250)
    chatCol:SetHeight(500)
    chatCol:SetPoint('TOPLEFT', advancedPanel, 'TOPLEFT', 40, -40)
    local chatTitle = AU.ui.Font(chatCol, 10, 'Chat', {1, 0.82, 0}, 'LEFT')
    chatTitle:SetPoint('TOPLEFT', chatCol, 'TOPLEFT', 0, 0)

    local c7 = AU.ui.Checkbox(chatCol, 'Profanity Filter', 16, 16, 'RIGHT')
    c7:SetPoint('TOPLEFT', chatTitle, 'BOTTOMLEFT', 0, -5)
    local c8 = AU.ui.Checkbox(chatCol, 'Spam Filter', 16, 16, 'RIGHT')
    c8:SetPoint('TOP', c7, 'BOTTOM', 0, 0)
    local c13 = AU.ui.Checkbox(chatCol, 'Chat Bubbles', 16, 16, 'RIGHT')
    c13:SetPoint('TOP', c8, 'BOTTOM', 0, 0)
    local c18 = AU.ui.Checkbox(chatCol, 'Party Chat Bubbles', 16, 16, 'RIGHT')
    c18:SetPoint('TOP', c13, 'BOTTOM', 0, 0)
    local c37 = AU.ui.Checkbox(chatCol, 'Creature Names', 16, 16, 'RIGHT')
    c37:SetPoint('TOP', c18, 'BOTTOM', 0, 0)
    local c46 = AU.ui.Checkbox(chatCol, 'Guild Recruitment', 16, 16, 'RIGHT')
    c46:SetPoint('TOP', c37, 'BOTTOM', 0, 0)
    local c38 = AU.ui.Checkbox(chatCol, 'Whisper Mode', 16, 16, 'RIGHT')
    c38:SetPoint('TOP', c46, 'BOTTOM', 0, 0)
    local c51 = AU.ui.Checkbox(chatCol, 'Sticky Channels', 16, 16, 'RIGHT')
    c51:SetPoint('TOP', c38, 'BOTTOM', 0, 0)
    local c68 = AU.ui.Checkbox(chatCol, 'Timestamps', 16, 16, 'RIGHT')
    c68:SetPoint('TOP', c51, 'BOTTOM', 0, 0)

    local raidCol = CreateFrame('Frame', nil, advancedPanel)
    raidCol:SetWidth(250)
    raidCol:SetHeight(500)
    raidCol:SetPoint('TOPLEFT', chatCol, 'TOPRIGHT', 20, 0)
    local raidTitle = AU.ui.Font(raidCol, 10, 'Raid & Party', {1, 0.82, 0}, 'LEFT')
    raidTitle:SetPoint('TOPLEFT', raidCol, 'TOPLEFT', 0, 0)

    local r47 = AU.ui.Checkbox(raidCol, 'Use Raid Frames', 16, 16, 'RIGHT')
    r47:SetPoint('TOPLEFT', raidTitle, 'BOTTOMLEFT', 0, -5)
    local r41 = AU.ui.Checkbox(raidCol, 'Show Raid Range', 16, 16, 'RIGHT')
    r41:SetPoint('TOP', r47, 'BOTTOM', 0, 0)
    local r48 = AU.ui.Checkbox(raidCol, 'Raid Health Text', 16, 16, 'RIGHT')
    r48:SetPoint('TOP', r41, 'BOTTOM', 0, 0)
    local r49 = AU.ui.Checkbox(raidCol, 'Raid Mana Text', 16, 16, 'RIGHT')
    r49:SetPoint('TOP', r48, 'BOTTOM', 0, 0)
    local r50 = AU.ui.Checkbox(raidCol, 'Target of Target', 16, 16, 'RIGHT')
    r50:SetPoint('TOP', r49, 'BOTTOM', 0, 0)

    local totDrop = AU.ui.Dropdown(raidCol, 'ToT Mode', 120, 20)
    totDrop:SetPoint('TOPLEFT', r50, 'BOTTOMLEFT', 5, 0)

    local combatCol = CreateFrame('Frame', nil, advancedPanel)
    combatCol:SetWidth(250)
    combatCol:SetHeight(500)
    combatCol:SetPoint('TOPLEFT', raidCol, 'TOPRIGHT', 20, 0)
    local combatTitle = AU.ui.Font(combatCol, 10, 'Combat Text', {1, 0.82, 0}, 'LEFT')
    combatTitle:SetPoint('TOPLEFT', combatCol, 'TOPLEFT', 0, 0)

    local ct52 = AU.ui.Checkbox(combatCol, 'Scrolling Combat Text', 16, 16, 'RIGHT')
    ct52:SetPoint('TOPLEFT', combatTitle, 'BOTTOMLEFT', 0, -5)

    local ctDrop = AU.ui.Dropdown(combatCol, 'Float Mode', 120, 20)
    ctDrop:SetPoint('TOPLEFT', ct52, 'BOTTOMLEFT', 5, -15)

    local ct53 = AU.ui.Checkbox(combatCol, 'Damage', 16, 16, 'RIGHT')
    ct53:SetPoint('TOPLEFT', ctDrop, 'BOTTOMLEFT', 16, 2)
    local ct54 = AU.ui.Checkbox(combatCol, 'Healing', 16, 16, 'RIGHT')
    ct54:SetPoint('TOP', ct53, 'BOTTOM', 0, 0)
    local ct55 = AU.ui.Checkbox(combatCol, 'Periodic Damage', 16, 16, 'RIGHT')
    ct55:SetPoint('TOP', ct54, 'BOTTOM', 0, 0)
    local ct56 = AU.ui.Checkbox(combatCol, 'Pet Damage', 16, 16, 'RIGHT')
    ct56:SetPoint('TOP', ct55, 'BOTTOM', 0, 0)
    local ct57 = AU.ui.Checkbox(combatCol, 'Spell Names', 16, 16, 'RIGHT')
    ct57:SetPoint('TOP', ct56, 'BOTTOM', 0, 0)
    local ct58 = AU.ui.Checkbox(combatCol, 'Miss Text', 16, 16, 'RIGHT')
    ct58:SetPoint('TOP', ct57, 'BOTTOM', 0, 0)
    local ct60 = AU.ui.Checkbox(combatCol, 'Dodge/Parry/Resist', 16, 16, 'RIGHT')
    ct60:SetPoint('TOP', ct58, 'BOTTOM', 0, 0)
    local ct63 = AU.ui.Checkbox(combatCol, 'Crushing/Glancing', 16, 16, 'RIGHT')
    ct63:SetPoint('TOP', ct60, 'BOTTOM', 0, 0)
    local ct64 = AU.ui.Checkbox(combatCol, 'Absorb', 16, 16, 'RIGHT')
    ct64:SetPoint('TOP', ct63, 'BOTTOM', 0, 0)
    local ct65 = AU.ui.Checkbox(combatCol, 'Resist', 16, 16, 'RIGHT')
    ct65:SetPoint('TOP', ct64, 'BOTTOM', 0, 0)
    local ct59 = AU.ui.Checkbox(combatCol, 'Block', 16, 16, 'RIGHT')
    ct59:SetPoint('TOP', ct65, 'BOTTOM', 0, 0)
    local ct69 = AU.ui.Checkbox(combatCol, 'Reputation', 16, 16, 'RIGHT')
    ct69:SetPoint('TOP', ct59, 'BOTTOM', 0, 0)
    local ct19 = AU.ui.Checkbox(combatCol, 'Low Health/Mana', 16, 16, 'RIGHT')
    ct19:SetPoint('TOP', ct69, 'BOTTOM', 0, -2)
    local ct11 = AU.ui.Checkbox(combatCol, 'Auras', 16, 16, 'RIGHT')
    ct11:SetPoint('TOP', ct19, 'BOTTOM', 10, 4)
    local ct9 = AU.ui.Checkbox(combatCol, 'Combo Points', 16, 16, 'RIGHT')
    ct9:SetPoint('TOP', ct11, 'BOTTOM', 0, 0)

    interfaceFrame:AddTab('Basic', function()
        basicPanel:Show()
        advancedPanel:Hide()
    end, 100)

    interfaceFrame:AddTab('Advanced', function()
        basicPanel:Hide()
        advancedPanel:Show()
    end, 100)

    -- callbacks
    local helpers = {}
    local callbacks = {}


    AU:NewCallbacks('interface', callbacks)
end)
